# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Justin Mello
title: Online Course Technologist
email: justin_mello@outlook.com
website: https://mello-j.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  mello-j
linkedin_username: justin-mello-1625jm

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  Hello and welcome to my Github page! My name is Justin and I'm an Online Course Technologist. I'm also a highly motivated and analytical professional with a diverse skill set in business analytics, project management, information technology, and customer support.
  This page aims to showcase some of my varied work experiences as well as professional and personal interests.

  I am most skilled in: <mark>Analytics</mark>, <mark>Project Management</mark>, and am developing <mark>Programming Skills</mark>. I'm currently working on a BS in Computer Science at Boise State University. <mark>Go Broncos!</mark>

content:
  - title: Professional Summary # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        description: | # this will include new lines to allow paragraphs
          Throughout my career, I have demonstrated a strong ability to lead and manage projects to successful outcomes, focusing on efficient communication, collaboration, and strategy. These projects have varied from Higher Education (helping deliver University courses on tight timelines) to the corporate world (system critical transitions).
          In all these experiences, I've learned that providing excellent support and communication throughout all stages of a project, to all involved stakeholders, is just as essential as the actual project "work"!

          For a brief accomplishments summary of my work career see the experiences section below. My full resume is available here: "[Justin Mello Resume](update link)"

          If you like the resume format, please refer to the original template by Colin McIntosh (S&G CEO of Sheets & Giggles in Grand Junction, CO). His original blog post can be found here: "[Sheets & Giggles is the fastest growing startup in CO!](update link)"
          If you like this GitHub pages theme, please view James Grant's GitHub page, where this theme "[Modern-Resume-Theme](https://github.com/sproogen)" is available among other super cool open-source projects!

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Online Course Technologist
        sub_title: Boise State University
        caption: August 2021 - Present
        description: | # this will include new lines to allow paragraphs
         blah blah blah

      - layout: left
        title: Transportation Analyst II
        sub_title: Boise Cascade
        caption: May 2015 - July 2021
        description: | # this will include new lines to allow paragraphs
         blah blah blah
         
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Boise State University
        caption: 2022 - 2025 (expected)
        sub_title: BS Computer Science
        description: | # this will include new lines to allow paragraphs
         After a significant formal education hiatus, I returned to school with the goal of completing a Bachelor of Science in Computer Science to expand my technical skills, knowledge of software development, databases, and mathematical analysis. I would like to integrate these skill sets and apply them in the business world while continuing my education into Graduate school.

         So far my coursework includes Calculus I, Calculus II, Discrete Mathematics, Computer Science I, Computer Science II, Software Development in C, Intro to Database Systems Usage, Intro to Version Control, Web Development, Navigating Computer Systems (Linux), and R programming.
         
      - layout: left
        title: Colorado Mesa University
        caption: 2011 - 2013
        sub_title: BA in Criminal Justice Minor in Psychology
        description: | # this will include new lines to allow paragraphs
         I completed my education in Grand Junction, CO graduating Summa Cum Laude with a GPA of 3.96 on a 4.0 scale. I managed to do this while working multiple part-time jobs (most notably as a Statistics Tutor and Data Analyst Intern!). I finished in 3 1/2 years with 142 credits, well over the requirements for my degree due to significant coursework taken in Statistics and Research Methods.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Beyond my professional and educational pursuits, I am an Avid Skier and Snowboarder (averaging 40+ days on the hill a year!). Bogus Basin is one of the best values out there, but I’m always drawn to the Mountain ranges of the Teton, Wasatch, the Sierra Nevada, the Rockies, and a visit to the Blue over in Eastern Oregon. 
      I’m still exploring the DIY opportunities out there where I’ve tinkered with car repair, bike repair, paddleboard repair (ever have a paddleboard blow a seam? It’s not pretty!), ski/snowboard maintenance, and other home projects. 
      For some reason along the way, I’ve formed a habit of collecting Funko Pops (mostly Star Wars and Marvel, with a few popular TV show characters thrown in).

      Enough talking! I invite you to check out my Resume, reach out to Contact me or grab a coffee, and hopefully soon explore some GitHub Repositories that showcase my coding projects, scripts, and contributions as I continue to develop my programming skills. 
      If you have any questions or would like to discuss potential collaborations or opportunities, please feel free to reach out. Thank you for visiting and I hope you’ve found value in this page!
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
