# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Justin Mello
title: Online Course Technologist
email: justin_mello@outlook.com
website: https://mello-j.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  mello-j
linkedin_username: justin-mello-1625jm

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  Hello and welcome to my Github page! My name is Justin and I'm an Online Course Technologist. I'm also a highly motivated and analytical professional with a diverse skill set in business analytics, project management, information technology, and customer support.
  This page aims to showcase some of my varied work experiences as well as professional and personal interests.

  I am most skilled in: <mark>Analytics</mark>, <mark>Project Management</mark>, and am developing <mark>Programming Skills</mark>

content:
  - title: Professional Summary # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title: Resume
            icon: fab fa-github
            url: replace
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Throughout my career, I have demonstrated a strong ability to lead and manage projects to successful outcomes, focusing on efficient communication, collaboration, and strategy. These projects have varied from Higher Education (helping deliver University courses on tight timelines) to the corporate world (system critical transitions).
          In all these experiences, I've learned that providing excellent support and communication throughout all stages of a project, to all involved stakeholders, is just as essential as the actual project "work"!

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Update me!
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
         blah blah blah
         
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Boise State University
        caption: 2022 - 2025 (expected)
        sub_title: BS Computer Science
        description: | # this will include new lines to allow paragraphs
         After a significant formal education hiatus, I returned to school with the goal of completing a Bachelor of Science in Computer Science to expand my technical skills, knowledge of software development, databases, and mathematical analysis. I would like to integrate these skill sets and apply them in the business world while continuing my education into Graduate school.

         So far my coursework includes: Calculus I, Calculus II, Discrete Mathematics, Computer Science I, Computer Science II, Software Development in C, Intro to Database Systems Usage, Intro to Version Control, Web Development, Navigating Computer Systems (Linux), and R programming.
         
      - layout: right
        title: Colorado Mesa University
        caption: 2011 - 2013
        sub_title: BA in Criminal Justice: Minor in Psychology
        description: | # this will include new lines to allow paragraphs
         I completed my education in Grand Junction, CO graduating Summa Cum Laude with a GPA of 3.96 on a 4.0 scale. I managed to do this while working multiple part-time jobs (most notably as a Statistics Tutor and Data Analyst Intern!). I finished in 3 1/2 years with 142 credits, well over the requirements for my degree due to significant coursework taken in Statistics and Research Methods.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
